<?xml version="1.0"?>
<package format="2">
  <name>barracuda_gamepad</name>
  <version>0.1.0</version>
  <description>Example package for template-repo demonstration</description>

  <maintainer email="ewang035@usc.edu">USC RoboSub Developer</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>joy</depend>
  <depend>std_msgs</depend>

  <export>
  </export>
</package>