services:
  barracuda-gamepad:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    container_name: barracuda-gamepad
    tty: true
    network_mode: host
    # volumes:
    #  - $HOME/.ssh:/root/.ssh